# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'a2' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  
pod 'SDWebImage/WebP'
pod 'SVProgressHUD', '~> 2.0'
  
end
